### ISSUE TITLE
Many Liked Dogs Causing Lag

### ISSUE THREAD

**Issue by ConnorMark** [Isaiahak/EECS-2311-Group-Project#106]
<img width="352" alt="EECS2311 - Bug Report 1" src="https://github.com/Isaiahak/EECS-2311-Group-Project/assets/157181976/7d981d6f-8192-4ac2-bc8b-1ab1a4330059">

**Comment by edsontakei** [comment]
Resolved by Ekatarina (reduced number of dogs) and Edson (implemented new logic for accelerating DB call on close)
